name: Download & Upload Videos

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install requests internetarchive

      - name: Install ffmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Run script
        run: python download.py

      - name: Commit processed.json
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add processed.json

          git diff --cached --quiet || (
            git commit -m "Update processed videos"
            git push
          )
